default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  url: postgres://developer:developer@localhost/livefac_dev

test:
  <<: *default
  url: postgres://developer:developer@localhost/livefac_tst

production:
  adapter: postgresql
  encoding: unicode
  url: postgres://mes:mes@localhost/mes
