# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7da74f6091b1e8a469992baf10b9f5b6a30515cf47115c862854358e0cbc94ea8b63e02e29f7a1d6d90eb60f4257eeb2f1d85a497cb94efcf8ce261634d9cd3c

test:
  secret_key_base: 4479344dc2f318278f80849ab1cd7f3ecc1d938b73430dc9d438d46733776702bf601586edb52243636628ad570f5548357c0358bd9cd0c9badfaf7a1e6ed04c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 7da74f6091b1e8a469992baf10b9f5b6a30515cf47115c862854358e0cbc94ea8b63e02e29f7a1d6d90eb60f4257eeb2f1d85a497cb94efcf8ce261634d9cd3f
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
